### ISSUE TITLE
&gt and &lt don't have correct color 

### ISSUE THREAD

**Issue by Smack66** [antfu/vscode-theme-vitesse#16]
### Describe the bug

![image](https://user-images.githubusercontent.com/93521974/200099486-4a450ae0-f9ee-421b-914c-abda7a3be633.png)

### Reproduction

use &gt and &lt

### System Info

```Shell
123
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
What do you expect?
