### ISSUE TITLE
Low contrast for certan sidebar folders on vitesse black

### ISSUE THREAD

**Issue by ElasticBottle** [antfu/vscode-theme-vitesse#21]
### Describe the bug

![image](https://user-images.githubusercontent.com/44563205/223407279-3d8ee76a-495e-4bd2-a52c-c9be8cb66395.png)

Not quite sure why, but certain folders have this really low contrast text color making things hard to read and I have not manage to find the right override to update the colors 😢 

### Reproduction

instal vitesse black and note the side bar options

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 3.62 GB / 7.60 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghsgz** [comment]
You can customize it in `settings.json` like this:

```json
"workbench.colorCustomizations": {
    "[Vitesse Dark]": {
        "list.activeSelectionBackground": "#fff",
        "list.inactiveSelectionBackground": "#fff",
    },
}
```

To see all related items about list/tree items style, you can checkout these two links:

- [vitesse-src#L55](https://github.com/antfu/vscode-theme-vitesse/blob/316babadf249404d9f2ddd4ef1e36fae19118d90/themes/vitesse-dark.json#L55)

- [vscode-doc/theme-color#lists-and-trees](https://code.visualstudio.com/api/references/theme-color#lists-and-trees)

**Comment by ElasticBottle** [comment]
@ghsgz  thanks so much for the speedy response. Tried both settings out, but I am, still see the same thing. 
One thing I'm noticing is that this is specifically for the folder that are included in the gitignore.

Is there anything extra being done there to override the list styling? 

Edit: Dug around more and found the much needed setting to override, thanks for pointing me in the right directions!

**Comment by ghsgz** [comment]
Seems like we don't have a clean and simple way to solve it.

in [src#L1053](https://github.com/antfu/vscode-theme-vitesse/blob/316babadf249404d9f2ddd4ef1e36fae19118d90/themes/vitesse-dark.json#L1053), we know that the related token is `markup.ignored`, and its foreground color is `#2f363d`, but we can not change it in `settings.json`.

```json
"editor.semanticTokenColorCustomizations": {
    "[Vitesse Dark]": {
        "rules": {
            "markup.ignored": {
                "foreground": "#ffffff"
            }
        }
    }
}
```

Cofigurations above do not work, semantic tokens only in \*editor\* can be customized like that.

You can hide file and dir matching in `.gitignore` via `"explorer.excludeGitIgnore": true`,
you can nesting silimar files to compact the whole project structure via `"explorer.fileNesting.enabled": true`,
but you can not tweak the style of ignored files.

Maybe you can try to change your mind to \*ignore\* these ignored files.

They do not matter.

Or, you can try to fork this theme, and modified the corresponding token and its property.

After all, open source comes with customization. :)

---

About the customization of semantic tokens, I found 2 links:

- https://github.com/microsoft/vscode/pull/29393
- [vscode/wiki/Semantic-Highlighting-Overview:define semantic theming rules in the user settings](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#as-a-theme-author-do-i-need-to-change-my-theme-to-make-it-work-with-semantic-highlighting:~:text=It%27s%20also%20possible%20to%20define%20semantic%20theming%20rules%20in%20the%20user%20settings%3A)
