### ISSUE TITLE
Higher contrast in the Vitesse Dark theme

### ISSUE THREAD

**Issue by ghost** [antfu/vscode-theme-vitesse#23]
### Clear and concise description of the problem

I've found that the contrast in Vitesse Dark is less. In Dark Soft it works due to the softer background, and black it obviously works with the vibrant, pure black.

However, I feel that the Dark Soft theme's background makes it hard to see the orange, yellow, and reds in the syntax.

### Suggested solution

I think the background color is great, just if the syntax colors' contrast could be raised, that'd be great.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't have a plan to change this theme much. You can always override some colors in your VS Code settings to fix your need.

**Comment by ghost** [comment]
Okay, thank you! Appreciate the quick response :)
