### ISSUE TITLE
关于主题风格颜色与示例图不一致的问题

### ISSUE THREAD

**Issue by christlee1989** [antfu/vscode-theme-vitesse#25]
在使用了全套antfu/vscode-settings的配置后，发现整体主题风格上与截图中的效果还是有些出入。

具体请看下面截图，左边是**我配置好的效果**，右边是**本仓库示例图**。

整体颜色似乎偏暗了一点，而且像 `=`、`()`、`{}`这些的颜色不一样。

想问问作者大大这部分的主题色彩是后面调整过吗？目标是想完美复制示例图中的效果！

PS：目前我用的主题是**Vitesse Black**，图2是使用**Vitesse Dark**的效果，然后下面图3是我的字体配置，不知道和作者是否一致。**图4是我的系统版本**。

<img width="1691" alt="image" src="https://github.com/antfu/vscode-theme-vitesse/assets/10151385/8d9c9ceb-d1e3-429c-8d91-15579d42dd2d">

<img width="1539" alt="image" src="https://github.com/antfu/vscode-theme-vitesse/assets/10151385/97941091-cef3-41ec-90e8-ccb701c517a4">

![image](https://github.com/antfu/vscode-theme-vitesse/assets/10151385/84155021-980b-4dbc-bc93-53e23fa29710)

<img width="141" alt="image" src="https://github.com/antfu/vscode-theme-vitesse/assets/10151385/1edb3295-d53e-46a3-8b77-fdfa0ea39c4a">

**Comment by antfu** [comment]
有些颜色调整过了。括弧的颜色用 `"editor.bracketPairColorization.enabled": false,` 关掉。
