### ISSUE TITLE
Any plan to support webstorm?

### ISSUE THREAD

**Issue by richerfu** [antfu/vscode-theme-vitesse#27]
### Clear and concise description of the problem

There is a unofficial plugin with vitesse theme in webstorm. Any official plan to support webstorm?

### Suggested solution

Support webstorm theme with latest design.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
No, I don't use WS. Feel free to port.
