### ISSUE TITLE
volar 更新到 2.0 以后 vue template 中的组件标签作用域发生了变化。现在 template 中的组件标签与 jsx 中的颜色不一致了。

### ISSUE THREAD

**Issue by yeyuqh** [antfu/vscode-theme-vitesse#32]
### volar 1.8.27
<img width="585" alt="截屏2024-03-05 09 42 22" src="https://github.com/antfu/vscode-theme-vitesse/assets/49150556/cbf69055-9ffe-41e9-8e51-527f9a532bee">

### volar > 2.0
<img width="579" alt="截屏2024-03-05 09 41 28" src="https://github.com/antfu/vscode-theme-vitesse/assets/49150556/8e3fb710-314c-400e-9397-99bf0efc189b">

### Suggested solution

.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't think there is anything I could do with it, you might want to report that to Volar, even tho I don't think it's a big issue anyway
