### ISSUE TITLE
Severe color deviation in Windows 11

### ISSUE THREAD

**Issue by Rawwhite** [antfu/vscode-theme-vitesse#35]
I'm not sure if this is a bug, or rather a problem with my configuration. I tried using the light theme in my daily use of the Windows system and found a significant deviation from the displayed rendering. I don't think this is a problem with my computer. I tried using another brand new Windows 11 computer and it also showed the same color deviation, but when I tried using the Ubuntu system, I didn't encounter this problem. The effect is as follows:

**In the Windows environment**
![image](https://github.com/antfu/vscode-theme-vitesse/assets/57385949/2b7dd91d-08c7-4743-89da-60123d23106e)

**In the Ubuntu environment**
![image](https://github.com/antfu/vscode-theme-vitesse/assets/57385949/1256e488-e82a-4f3b-ac69-5b44ac9272d9)

I really like this theme and hope it can help me solve this problem or provide possible solutions

> System: Windows 11
VSCode version：1.90.2
Vitesse Theme：0.8.0

**Comment by antfu** [comment]
I don't know - and honestly there is nothing I can help - this repo is just a bunch of hex colors - we can't define how they are rendered. Issue tracker is for tracking bugs not for questions, btw.

**Comment by Rawwhite** [comment]
Thank you very much for your answer! Also sorry, I don't seem to know enough about elegantly asking questions, I'll go back and learn, thanks again!

> I don't know - and honestly there is nothing I can help - this repo is just a bunch of hex colors - we can't define how they are rendered. Issue tracker is for tracking bugs not for questions, btw.
