### ISSUE TITLE
Color palette

### ISSUE THREAD

**Issue by stag-enterprises** [antfu/vscode-theme-vitesse#37]
### Clear and concise description of the problem

No color guide exists.

### Suggested solution

It would be nice if a color palette and guide was supplied, to make developing themes for other applications eaiser.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I didn't use a color palette, this file might be close to that https://github.com/antfu/vscode-theme-vitesse/blob/main/scripts/colors.ts

**Comment by stag-enterprises** [comment]
> I didn't use a color palette, this file might be close to that [`main`/scripts/colors.ts](https://github.com/antfu/vscode-theme-vitesse/blob/main/scripts/colors.ts?rgh-link-date=2024-11-04T04%3A45%3A14Z)

Alright I'll take a look. Thanks!
